seed: 6527
dataset_name: walker-step
dataset_dir: data/behavior_data/walker_step/
is_video_data: false
frame_stack: 3
image_size: 64

# domain description
domain_description_file: config/domain_description/walker_step_env.yaml

# the information will be populated automatically
attr_info: null

# if needed, select subsets of the training/test data
attr_training_subset: null
attr_test_subset: null

encoder_cfg: null

attr_func:
  expr_id: attr-func-walker-step_20220901_230656
  encoder_path: null
  n_ensemble: 1
  reward_clip: 20
  state_dim: 24
  attr_dim: 2
  hidden_dim: 512
  is_global_ranking: true
  batch_size: 128
  eval_batch_size: 128
  n_epoch: 3
  sampling_strategy: uniform
  weight_decay: 1.0e-05
  lr: 0.0001
  sche: cosine
  cosine_sche:
    min_lr: 1.0e-05
  step_sche:
    step_size: 20
    gamma: 0.5
  encoded_attributes:
    step_size:
      max: 19.434894561767578
      min: -0.5840741395950317
      ground_min: 0.11998900897908225
      ground_max: 1.2591199050430817
      key: final_step_size
      id: 0
      epsilon: 0.1
      reverse: false
    softness:
      max: -1.5320990085601807
      min: -15.05331802368164
      ground_min: 0.033633231543276465
      ground_max: 0.15837152416873368
      key: softness_speed
      id: 1
      epsilon: 0.015
      reverse: true
reward_func:
  expr_id: null
  attr_func_path: trained_models/walker_step/method_1/attr_func/
  n_targets_per_pair: 50
  n_targets_per_pair_eval: 2
  n_epoch: 3
  batch_size: 128
  eval_batch_size: 128
  reward_clip: 20
  state_dim: 24
  attr_dim: 2
  hidden_dim: 512
  weight_decay: 1.0e-05
  lr: 0.0001
  sche: cosine
  cosine_sche:
    min_lr: 1.0e-05
  step_sche:
    step_size: 20
    gamma: 0.5
