seed: 4295
dataset_name: walker-step
dataset_dir: data/behavior_data/walker_step/
is_video_data: false
frame_stack: 3
image_size: 64
use_language_attr: true
domain_description_file: config/domain_description/walker_step_env.yaml
attr_info:
  use_global_ranking: true
  is_video_data: false
  attributes:
    step_size:
      key: final_step_size
      language_descriptions:
      - the step size
      id: 0
      epsilon: 0.1
      reverse: false
      local_change_range:
        lower: 1.0
        upper: 1.1
    softness:
      key: softness_speed
      language_descriptions:
      - softness of the movement
      id: 1
      epsilon: 0.015
      reverse: true
      local_change_range:
        lower: 1.0
        upper: 1.1
attr_training_subset: null
attr_test_subset: null
encoder_cfg: null
reward_func:
  expr_id: language-reward-func-walker-step_20220926_220040
  encoder_path: null
  n_negative_training: 100
  n_negative_test: 100
  two_direction: true
  reward_clip: 20
  state_dim: 24
  attr_dim: 768
  hidden_dim: 1024
  anchor_hidden_dim: 128
  anchor_emb_dim: 64
  batch_size: 512
  eval_batch_size: 512
  max_batch_epoch: 440
  n_epoch: 12
  sampling_strategy: uniform
  weight_decay: 1.0e-05
  lr: 0.0001
  sche: cosine
  cosine_sche:
    min_lr: 1.0e-05
  step_sche:
    step_size: 20
    gamma: 0.5
  online_training_sampling_strategy: uniform
  encoded_attributes:
    step_size:
      key: final_step_size
      language_descriptions:
      - the step size
      id: 0
      epsilon: 0.1
      reverse: false
      local_change_range:
        lower: 1.0
        upper: 1.1
    softness:
      key: softness_speed
      language_descriptions:
      - softness of the movement
      id: 1
      epsilon: 0.015
      reverse: true
      local_change_range:
        lower: 1.0
        upper: 1.1
